[tool.poetry]
name = "maze"
version = "0.0.0"
description = "Maze"
authors = ["Eric Chiang <serixscorpio@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/serixscorpio/maze"
repository = "https://github.com/serixscorpio/maze"
documentation = "https://maze.readthedocs.io"
classifiers = ["Development Status :: 1 - Planning"]

[tool.poetry.urls]
Changelog = "https://github.com/serixscorpio/maze/releases"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
attrs = "^21.4.0"
Pillow = "^9.1.1"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
types-Pillow = "^9.0.16"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = { extras = ["toml"], version = "^6.1" }
safety = "^1.10.3"
mypy = "^0.910"
typeguard = "^2.13.2"
sphinx = "^4.3.2"
sphinx-autobuild = ">=2021.3.14"
pre-commit = "^2.15.0"
flake8 = "^4.0.1"
black = ">=22.3.0"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.4.25"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.5"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
reorder-python-imports = "^3.1.0"
pre-commit-hooks = "^4.0.1"
sphinx-click = "^4.0.3"
Pygments = "^2.12.0"
pyupgrade = "^2.32.0"
furo = ">=2022.4.7"

[tool.poetry.scripts]
maze = "maze.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["maze"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
