[tool.poetry]
name = "maze"
version = "0.0.0"
description = "Maze"
authors = ["Eric Chiang <serixscorpio@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/serixscorpio/maze"
repository = "https://github.com/serixscorpio/maze"
classifiers = ["Development Status :: 1 - Planning"]

[tool.poetry.urls]
Changelog = "https://github.com/serixscorpio/maze/releases"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
attrs = "^22.1.0"
Pillow = "^9.2.0"
fastapi = "^0.81.0"
uvicorn = "^0.18.3"
types-Pillow = "^9.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
coverage = {version = "^6.4.1", extras = ["toml"]}
safety = "^2.1.1"
mypy = "^0.971"
typeguard = "^2.13.2"
pre-commit = "^2.20.0"
flake8 = "^5.0.4"
black = "^22.8.0"
flake8-bugbear = "^22.8.23"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.7"
pep8-naming = "^0.13.0"
darglint = "^1.8.1"
reorder-python-imports = "^3.8.2"
pre-commit-hooks = "^4.3.0"
Pygments = "^2.13.0"
pyupgrade = "^2.37.3"
bandit = "^1.7.4"

[tool.poetry.scripts]
maze = "maze.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["maze"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
